### ISSUE TITLE
GSHEET : Implémenter export bon de commande > ODOO

### ISSUE THREAD

**Issue by mudounet** [mudounet/coopalim-odoo#1]
Le format compatible est décrit dans fichier commande.csv@6dfcd7b7b

**Comment by mudounet** [comment]
Dans le bon de commande Google Sheets, J'ai défini les clefs qui permettent d'avoir les informations nécessaires :
 - Colonne D7:D57 : Clefs des produits
 - Colonne P1:CZ1 : Clefs des adhérents

**Comment by mudounet** [comment]
Je t'ai crée la branche feature/impl_import_commandes (surtout pour la structure de fichier)

**Comment by Giorgiolino** [comment]
@mudounet 
Dans le Document Google Sheet des commandes, tu devrais maintenant avoir une entrée de menu "Coopalim" (menu déroulant) avec une sous-entrée "Exporter les commandes". Pour l'instant cela crée un onglet avec les commandes au format cible pour Odoo. Je vais regarder pour exporter cela en csv, cela devrait être possible. A chaque fois que tu fais un export, il est horodaté à la seconde près.

**Comment by mudounet** [comment]
C'est pas mal du tout. Juste un truc, est-ce que pour l'ID, tu pourrais faire un truc du genre 2018_<mois><jour>_<nbre de minutes>_<NomDeLaPersonne> ? ça serait plus lisible, non? Enfin, il faudrait ajouter d'autres champs, comment faire?

**Comment by mudounet** [comment]
Je considère que c'est fini... Comment on capitalise le truc?

**Comment by Giorgiolino** [comment]
"Comment on capitalise le truc ?" --> Peut-être en enregistrant le script Google Script sous git.
"[...] pour l'ID, tu pourrais faire un truc du genre 2018_" --> Ce que tu suggères c'est que l'horodatage sépare année mois et jours (ex. 2018_02_17) ou alors de n'avoir que "2018_" comme souche et que le reste soit autre chose ? Dans mon idée, une souche telle que "20180216" a plus de sens car elle pourrait correspondre à la date de clôture des commandes, ce qui permettrait de faire plus facilement les rapprochements.

**Comment by mudounet** [comment]
100% OK avec ta proposition. 

Je propose :
https://gitlab.com/coopalim/coopalim-internal

Je propose un répertoire **outils**, puis **info**, puis **google-sheet**. Qu'en penses-tu?

**Comment by Giorgiolino** [comment]
Le script d'export est désormais journalisé dans le dépôt [coopalim-internal](https://gitlab.com/coopalim/coopalim-internal)
