### ISSUE TITLE
Uniformiser la liste des adhérents

### ISSUE THREAD

**Issue by mudounet** [mudounet/coopalim-odoo#11]
J'ai d'ores et déjà une demande à faire remonter au groupe financement, qui gère la liste de membres (Michèle), afin d'optimiser le travail en aval. Tu as déjà des compétences en Excel, tu comprendras donc de quoi je veux parler ci-dessous:

 - Créer une colonne **id** (CP_+un numéro unique sur 7 chiffres) : C'est le numéro d'adhérent. On va l'utiliser partout. Ainsi, il y aura moins de problèmes de confidentialité pour les documents sur internet (Commandes, etc.)
 - Garder les colonnes **nom** et **prénom** séparées. Le prénom avec premier caractère en majuscule, pour favoriser la lisibilité. Le nom est lui entièrement en majuscules
 - Créer une colonne **name** : colonnes **prénom** ** plus **nom**, séparés par un espace.
 - la colonne **email** contient les emails
 - la colonne **tel** contient le numéro de téléphone
 - Créer une colonne **login**, avec la première lettre du prénom en majuscule, le nom en majuscule (ex: GMANCIET pour Guillaume MANCIET).
 - conserver tous les autres champs qui sont intrinsèques à la personne (date naissance, adresse) dans cette feuille. Il les utilisera plus tard (à renommer, par ex: **membres** ou **coopérateurs**).

**Déplacer les colonnes de statistiques dans d'autres onglets (ex : stats), ainsi que les colonnes de suivi de la comptabilité (ex : cotisations).**

**Comment by renttro** [comment]
J'ai fait un fichier Xlsx répondant aux critères ci-dessus. Est-ce que je le dépose ici ?

**Comment by Giorgiolino** [comment]
@renttro 
S'il contient les nom/prénom des adhérents (je penses que c'est le cas), il vaut mieux nous le transmettre par mail dans un premier temps. On avisera ensuite.

**Comment by renttro** [comment]
Voici en attaché le fichier de la liste des adhérents à importer sur Chimpmail. C’est un fichier tabulé. Le champ ID est à importer en format Text
Laurent

**Comment by renttro** [comment]
En attaché un fichier Excel avec plusieurs onglets permettant de générer en faisant un copier-coller dans l’onglet « original »:
- la mailinglist pour gmail dans l’onglet « Maillist_pregmailpv.csv » : Il suffira ensuite d’enregistrer cette feuille uniquement en format csv séparateur point-virgule. Le nom du fichier .csv devra être changé en .txt pour pouvoir être importé par gmail
- la mailinglist pour MailChimp dans l’onglet « Maillist_prechimp.txt » : Il suffira ensuite d’enregistrer cette feuille uniquement en format texte séparateur tabulation. Le fichier .txt est directement importable dans MailChimp en définissant le champ ID comme un champ Text
- les onglets "#11"  et "#11 stat" contiennent le tableau répondant aux spécifications de #11

Les 4 onglets autres que « original » sont construit à partir de ce dernier à l’aide de fonctions. Pour ajouter des membres ou renouveler la liste il suffit de faire un copier collé partiel ou total  de la liste dans l’onglet « original » en respectant le format original et de rajouter dans les autres onglets autant de lignes que nécessaire en faisant un sélection/glissé de la dernière ligne.
Ainsi les listes peuvent être mise à jour suivant chacun des formats à partir de l’onglet « original »

Cela serait pratique d’avoir un espace cloud d’échange de fichiers. ;-)
A+
Laurent

**Comment by mudounet** [comment]
@renttro : Est-ce que tu connais GIT?

**Comment by mudounet** [comment]
Il s'agit de formater le fichier source (celui que Michèle possède), ainsi que de former les personnes gérant ce fichier, parce que le problème va se reposer tant que l'ensemble des fichiers ne respecteront pas le format ci-dessus.

**Comment by renttro** [comment]
Non pas vraiment. Donne moi un lien je regarderais. 

Laurent

**Comment by Irishclem07** [comment]
Ok je prends la main et fais le point avec Michèle

**Comment by mudounet** [comment]
Au fait, il est possible d'utiliser ceci:

https://support.office.com/fr-fr/article/cr%C3%A9ation-ou-suppression-d-un-tableau-excel-e81aa349-b006-4f8a-9806-5af9df0ac664

puis 

https://support.office.com/fr-fr/article/utilisation-de-r%C3%A9f%C3%A9rences-structur%C3%A9es-avec-des-tableaux-excel-f5ed2452-2337-4f71-bed3-c8ae6d2b276e

**Comment by Irishclem07** [comment]
Aujourd'hui nous avons travaillé avec Michèle et paramétré le le fichier tel que demandé.
Onglet Saisie Membres = Onglet réservé à la saisie pour Michèle
Onglet Membres = Onglet correspondant aux besoins soulevés du #11
Onglet Statistiques = Quelques statistiques provenant de l'onglet saisie. Encore en cours de finalisation mais si je dois le finir il faudrait me donner la main en modification sur le fichier car j'y ai juste accès en lecture seule.

Merci de me faire un retour si cela correspond bien aux attentes

**Comment by renttro** [comment]
Salut Guillaume,
Merci encore pour l’autre soir, c’était vraiment très riche en découverte et apprentissage. J’essaye à présent de revoir un peu tout cela. 
J’ai fait une série de test avec SourceTree. Je rencontre un problème quand je modifie et commit alternativement deux fichiers et qu’à un moment je me rends compte par exemple que les deux dernières modifications sur le 2ième fichier sont à supprimer mais par contre je veux garder la  dernière version du premier fichier. J’ai bien compris qu'en double cliquant sur les différents noeuds du graphe j’arrive à me déplacer entre les différentes versions mais je ne trouve pas moyen de rassembler des versions différentes des deux fichiers.
Je n’ai pas trouvé d’info là dessus. Peux-tu m’expliquer comment opérer ?
Merci bien
Laurent

**Comment by mudounet** [comment]
Merci, beau boulot. Je crée un nouveau ticket, pour faire quelques améliorations
