### ISSUE TITLE
XLS : Générer la liste des membres format gmail

### ISSUE THREAD

**Issue by mudounet** [mudounet/coopalim-odoo#12]
A faire en tenant compte des infos dans #11 :
- dans un format qui te permets de les récupérer dans un autre compte gmail

**Comment by renttro** [comment]
J'ai créé un fichier .csv importable par gmail contenant juste les prénom, nom et adresse mail.
Or je viens de découvrir #11 ou il y a beaucoup plus d'infos dont des champs (par exemple la colonne id) qui n'existent pas par défaut dans gmail. Est-ce que je suis strictement le format décrit dans #11 ou le but est juste de charger les adresses mails dans gmail ?

**Comment by mudounet** [comment]
Pour cette moulinette, le but est "juste" d'importer les mails. Je n'ai pas gmail personnellement, mais est-ce qu'il serait possible, dans gmail, d'avoir cet ID en tant que commentaire? Dans ce cas, cela pourrait être intéressant d'avoir la possibilité d'importer, avec cet outil, cet ID en tant que commentaire...

**Comment by renttro** [comment]
Voilà la liste des membres en format txt importable sur gmail avec: Nom, prénom, adresse mail, CP_000numéroAdhérent sous ID à partir de la liste de 110 membre au 28/01/2018

**Comment by mudounet** [comment]
ok, j'ai vu. J'ai effacé le fichier joint (données confidentielles). Quel est le mode d'emploi?

**Comment by renttro** [comment]
Mode d'emploi ? Que veux-tu dire ? Le fichier joint était dans le format permettant d'être importé dans un carnet d'adresse d'un compte Gmail. 
Me demandes-tu comment je l'ai obtenu à partir du tableau Excel ?
Laurent

**Comment by mudounet** [comment]
@Giorgiolino ,@renttro : Il faut trouver un moyen simple de partager l'algorithme avec les autres membres. Moi par exemple je n'ai qu'OpenOffice sur mon PC...

Une piste de réponse : En fait, je pense que l'on pourrait s'arranger pour que les fichiers soient toujours générés par le fichier Maître de Michelle. Il y aurait donc un onglet MailChimp et Gmail qui seraient mis à a jour automatiquement à chaque fois que Michèle clique sur sauvegarder... Ca serait pas mal, non?

**Comment by Giorgiolino** [comment]
@mudounet @renttro 
> je pense que l'on pourrait s'arranger pour que les fichiers soient toujours générés par le fichier Maître 

Je penses que c'est la bonne stratégie à employer. Quant à savoir la localisation du fichie en question (poste de travail chez Michèle, en ligne avec accès réservés, etc) --> à voir.

> Il y aurait donc un onglet MailChimp et Gmail

OK. Voire d'autres selon les besoins à venir.

> [...] qui seraient mis à a jour automatiquement à chaque fois que Michèle clique sur sauvegarder

J'ai une idée de comment faire cela avec Excel (macros sans doute). J'ai également une idée de comment le faire avec Google Sheets. Par contre je réalise à l'instant que si les données sont centralisées (et en accès restreint bien sûr) l'on peut s'arranger pour que chaque personne ait accès aux données dont il a besoin sans avoir à demander à Michèle ou quiconque d'envoyer celles_ci. Exemple : J'ai besoin de la liste des contacts à jours pour la Newletter; en l'état actuel des choses, il faudrait que je contacte Michèle mais aussi que je farfouille du côté de la boîte mail voire ailleurs.

Du coup moi je suggérerais un document en ligne (centralisé donc) mais offrant un mode hors-ligne (autonomie et non-dépendance à internet pour y bosser).

Qu'en pensez-vous ?

**Comment by renttro** [comment]
> Le 31 janv. 2018 à 11:48, giorgiolino <notifications@github.com> a écrit :
> 
> Du coup moi je suggérerais un document en ligne (centralisé donc)
> 
Tu penses à quoi ? A un fichier sur un cloud ou sur un outil tel que Google sheet ? En tous les cas je trouve que l'idée mérite d'être explorée. 
> mais offrant un mode hors-ligne (autonomie et non-dépendance à internet pour y bosser).
> 
> Qu'en pensez-vous ?
