### ISSUE TITLE
XLS : Générer csv au format mailchimp

### ISSUE THREAD

**Issue by mudounet** [mudounet/coopalim-odoo#13]
A faire en tenant compte des infos dans #11 :

- dans un format compatible avec outlook, mailchimp, etc

**Comment by renttro** [comment]
fichier Text tabulé généré pour importation sur Chimpmail. Pour importer les ID, il faut définir un champ Text. J'ai testé, cela fonctionne. J'envoie le fichier en attaché par mail

**Comment by mudounet** [comment]
@Giorgiolino, @renttro, j'ai pas trop suivi... Les fichiers sont générés, OK. Comment faire pour mutualiser pour que les autres puissent également utiliser l'algorithme, pour générer les listes, lorsque c'est nécessaire?

On mets tout cela sous GIT? Une meilleure idée?
